#!/bin/bash

#####################################################
PREFIX=/usr/share/cdr_stats
PID_PREFIX=/var/run

VENV_ON=/usr/share/virtualenvs/cdr-stats/bin/activate
VENV_OFF=deactivate
SOCKETIO_SERVER=$PREFIX/socketio_server.py
SOCKETIO_SERVER_PIDFILE=$PID_PREFIX/cdr-stats-socketio-server.pid
#####################################################

#TEST
PREFIX=/home/areski/public_html/django/MyProjects/django_asterisk-stat/cdr-stats/cdr_stats
PID_PREFIX=/tmp
VENV_ON=/home/areski/.virtualenvs/cdrstats/bin/activate
SOCKETIO_SERVER=$PREFIX/run_socketio.py
SOCKETIO_SERVER_PIDFILE=$PID_PREFIX/cdr-stats-socketio-server.pid


do_help()
{
	echo
	echo "$(basename $0) (start|stop|restart|status|reload)"
	echo
	exit 1;
}

do_installerror()
{
	echo
	echo "Error : We cannot locate the file $SOCKETIO_SERVER"
	echo
	exit 1;
}

do_start()
{
	NICE=$(which nice)
	server_already_running="false"
	$VENV_OFF &>/dev/null
	source $VENV_ON
	
	kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
	if [ $? -eq 0 ]; then
		echo "$SERVER_NAME already running"
		server_already_running="true"
	else
		$NICE --adjustment=-10 $SOCKETIO_SERVER -d -p $SOCKETIO_SERVER_PIDFILE
	fi
	
	if [ "$server_already_running" = "true" ]; then
		$VENV_OFF &>/dev/null
		exit 0
	fi
	
	sleep 1s
	if [ "$server_already_running" = "false" ]; then
		kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
			&& echo "$SERVER_NAME started" || echo "$SERVER_NAME start failed"
	fi
	$VENV_OFF &>/dev/null
}


do_stop()
{
	kill -TERM $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
	if [ $? -eq 0 ]; then
		echo "$SERVER_NAME stopped"
		rm -f $SOCKETIO_SERVER_PIDFILE
	else
		echo "$SERVER_NAME stopping failed"
	fi
}

do_reload()
{
	kill -HUP $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
	if [ $? -eq 0 ]; then
		echo "$SERVER_NAME reloaded"
	else
		echo "$SERVER_NAME reload failed"
	fi
}


do_status()
{
    echo "status..."
	kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
		&& echo "$SERVER_NAME running" || echo "$SERVER_NAME not running"
}


# main #
echo "$SOCKETIO_SERVER"

[ -x $SOCKETIO_SERVER ] || do_installerror

mkdir -p $PID_PREFIX 2>/dev/null

SERVER_NAME="CDR-Stats-SocketIO-Server"


case $1 in
start)
	do_start
;;

stop)
	do_stop
;;

restart)
	do_stop
	sleep 0.5s
	do_start
;;

status)
	do_status
;;
reload)
	do_reload
;;
*)
	do_help
;;
esac
